version: '3'

networks:
  hq_dmz_net:
    ipam:
      driver: default
      config:
        - subnet: 172.16.123.128/28
          gateway: 172.16.123.129

  hq_private_net:
    ipam:
      driver: default
      config:
        - subnet: 10.0.1.0/24
          gateway: 10.0.1.1

  isp_net:
    ipam:
      driver: default
      config:
        - subnet: 172.30.255.0/24
          gateway: 172.30.255.1

  shop_a_net:
    ipam:
      driver: default
      config:
        - subnet: 172.31.255.0/29
          gateway: 172.31.255.1

services:
  hq_server:
    build: ./nginximage
    volumes:
      - ./www/internal:/usr/share/nginx/html:ro
    networks:
      hq_dmz_net:
        ipv4_address: 172.16.123.130
    environment:
      - DEFAULT_ROUTE=172.16.123.142
    cap_add:
       - NET_ADMIN

  # TODO: default route setup via edge router `ip r r default via 172.16.123.142`
  dns_server:
    build: ./dns
    volumes:
      - ./dns/conf:/etc/bind
      - /var/cache/bind
      - /var/lib/bind
      - ./dns/logs/:/var/logs
    networks:
      hq_dmz_net:
        ipv4_address: 172.16.123.131
    cap_add:
      - NET_ADMIN
    restart: always

  vpn_server:
    image: lscr.io/linuxserver/wireguard:latest
    cap_add:
      - NET_ADMIN
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Etc/UTC
      - PEERS=1
      - INTERNAL_SUBNET=10.0.1.16
      - ALLOWEDIPS=10.0.1.0/24,172.16.123.132
      - PERSISTENTKEEPALIVE_PEERS=all
    networks:
      hq_dmz_net:
        ipv4_address: 172.16.123.132
    volumes:
      - ./wireguard/config:/config
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    restart: unless-stopped

  hq_edge_router:
    build: ./baseimage
    networks:
      isp_net:
        ipv4_address: 172.30.255.253
      hq_dmz_net:
        ipv4_address: 172.16.123.142
    environment:
      - DEFAULT_ROUTE=172.30.255.254
      - ROUTES=10.0.1.0/24:172.16.123.141;
      - NAT=10.0.1.0/24
      - INTERN_INTERFACE=eth0
      - DMZ=172.16.123.128/28
    cap_add:
      - NET_ADMIN

  isp_router:
    build: ./baseimage
    networks:
      isp_net:
        ipv4_address: 172.30.255.254
    environment:
      - ROUTES=172.16.123.128/28:172.30.255.253;
    cap_add:
      - NET_ADMIN

  shop_a_router:
    build: ./baseimage
    networks:
      isp_net:
        ipv4_address: 172.30.255.2
      shop_a_net:
        ipv4_address: 172.31.255.6
    environment:
      - DEFAULT_ROUTE=172.30.255.254
      - NAT=172.31.255.0/29
      - INTERN_INTERFACE=eth1
    cap_add:
      - NET_ADMIN

  shop_a_client:
    build: ./baseimage
    networks:
      shop_a_net:
        ipv4_address: 172.31.255.2
    dns:
      - 172.16.123.131
    environment:
      - DEFAULT_ROUTE=172.31.255.6
    sysctls:
      - net.ipv4.conf.all.src_valid_mark=1
    cap_add:
      - NET_ADMIN
  
  hq_private_router:
    build: ./baseimage
    networks:
      hq_dmz_net:
        ipv4_address: 172.16.123.141
      hq_private_net:
        ipv4_address: 10.0.1.254
    environment:
      - DEFAULT_ROUTE=172.16.123.142
    cap_add:
      - NET_ADMIN
  
  hq_private_server:
    build: ./nginximage
    volumes:
      - ./www/internal:/usr/share/nginx/html:ro
    networks:
      hq_private_net:
        ipv4_address: 10.0.1.2
    environment:
      - DEFAULT_ROUTE=10.0.1.254
    cap_add:
      - NET_ADMIN
